repos:

  - repo: https://github.com/executablebooks/mdformat
    rev: 0.7.22
    hooks:
      - id: mdformat
        additional_dependencies:
          - mdformat-frontmatter
          - mdformat-gfm

  - repo: https://github.com/igorshubovych/markdownlint-cli
    rev: v0.45.0
    hooks:
      - id: markdownlint
        files: "^docs/.*\\.md$"


  - repo: https://github.com/errata-ai/vale
    rev: v3.12.0
    hooks:
      - id: vale
        files: "^docs/.*\\.(md|txt)$"

  - repo: local
    hooks:
      - id: check-markdown-links
        name: Check Markdown links
        entry: python scripts/check_markdown_links.py
        language: python
        files: "^docs/.*\\.md$"
        additional_dependencies: ['requests']
