site_name: Nginx Security Monitor Documentation
site_description: Comprehensive documentation for Nginx Security Monitor - Real-time threat detection and response for nginx web servers
site_url: https://nginx-security-monitor.github.io/
repo_url: https://github.com/nginx-security-monitor/nginx-security-monitor
repo_name: nginx-security-monitor/nginx-security-monitor
edit_uri: edit/main/docs/

# Copyright
copyright: Copyright &copy; 2024-2025 Nginx Security Monitor Contributors

# Configuration
theme:
  name: material
  
  # Theme features
  features:
    - announce.dismiss
    - content.action.edit
    - content.action.view
    - content.code.annotate
    - content.code.copy
    - content.code.select
    - content.tabs.link
    - content.tooltips
    - header.autohide
    - navigation.expand
    - navigation.footer
    - navigation.indexes
    - navigation.instant
    - navigation.instant.prefetch
    - navigation.instant.progress
    - navigation.prune
    - navigation.sections
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow
    - toc.integrate
  
  # Color palette
  palette:
    - scheme: default
      primary: blue
      accent: blue
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      primary: blue
      accent: blue
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  
  # Fonts
  font:
    text: Roboto
    code: Roboto Mono
  
  # Favicon and logo
  favicon: imgs/favicon.ico
  logo: imgs/logo.png
  
  # Language
  language: en

# Plugins
plugins:
  - search:
      separator: '[\s\-,:!=\[\]()"`/]+|\.(?!\d)|&[lg]t;|(?!\b)(?=[A-Z][a-z])'
  - minify:
      minify_html: true
  - git-revision-date-localized:
      enable_creation_date: true
      type: timeago
      fallback_to_build_date: true
  - awesome-pages
  - macros
  - tags

# Customization
extra:
  analytics:
    provider: google
    property: !ENV [GOOGLE_ANALYTICS_KEY, ""]
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/nginx-security-monitor/nginx-security-monitor
    - icon: fontawesome/brands/docker
      link: https://hub.docker.com/r/nginx-security-monitor/nginx-security-monitor
    - icon: fontawesome/solid/paper-plane
      link: mailto:security@nginx-security-monitor.com
  version:
    provider: mike
    default: stable

# Extensions
markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - toc:
      permalink: true
      title: On this page
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
      emoji_index: !!python/name:material.extensions.emoji.twemoji
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink:
      repo_url_shorthand: true
      user: nginx-security-monitor
      repo: nginx-security-monitor
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

# Page tree
nav:
  - Home: index.md
  - Getting Started:
    - Overview: getting-started.md
    - Installation: INSTALLATION.md
    - Quick Start: QUICK_START_TUTORIAL.md
    - Configuration: CONFIGURATION.md
  
  - User Guide:
    - Use Cases: USE_CASES.md
    - Security Features: SECURITY_FEATURES.md
    - Pattern Detection: PATTERN_DETECTION.md
    - Alert Systems: ALERT_SYSTEMS.md
    - Mitigation Strategies: MITIGATION_STRATEGIES.md
    - Service Protection: SERVICE_PROTECTION.md
  
  - Configuration:
    - Configuration System: CONFIGURATION_SYSTEM.md
    - Encryption Guide: ENCRYPTION_GUIDE.md
    - Security Integrations: SECURITY_INTEGRATIONS.md
    - Integration Cookbook: INTEGRATION_COOKBOOK.md
  
  - Operations:
    - Operations Guide: OPERATIONS_GUIDE.md
    - Deployment:
      - Overview: deployment/README.md
      - Development: deployment/development.md
    - Performance Tuning: operations/performance-tuning.md
    - Monitoring & Logging: operations/monitoring.md
    - Disaster Recovery: operations/disaster-recovery.md
  
  - Development:
    - Contributing: CONTRIBUTING.md
    - Architecture: ARCHITECTURE.md
    - Plugin Development: PLUGIN_DEVELOPMENT.md
    - Testing: TESTING.md
    - Style Guide: STYLE_GUIDE.md
    - Architecture Decisions:
      - Overview: architecture/decisions/README.md
      - ADR Template: architecture/decisions/template.md
  
  - API Reference:
    - Overview: api/index.md
    - API Reference: API_REFERENCE.md
    - Versioning: api/versioning.md
  
  - Process Documentation:
    - Release Process: process/releases.md
  
  - Security:
    - Best Practices: security/best-practices.md
  
  - Troubleshooting:
    - Common Issues: troubleshooting/common-issues.md
    - Installation Issues: troubleshooting/installation-issues.md
    - Network Issues: troubleshooting/network-issues.md
    - Troubleshooting Guide: TROUBLESHOOTING.md
  
  - About:
    - License: LICENSE.md
    - Code of Conduct: CODE_OF_CONDUCT.md
    - Testing Keys: TESTING_KEYS.md

# Extra CSS
extra_css:
  - stylesheets/extra.css

# Extra JavaScript
extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
  - javascripts/shortcuts.js
