version: '3'
services:
  nginx:
    build:
      context: ../../
      dockerfile: examples/nginx-dev/Dockerfile
    ports:
      - "8081:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./html:/usr/share/nginx/html:ro
      - ./logs:/var/log/nginx
      - ./config:/opt/nginx-security-monitor/config
      # - ./scripts:/opt/nginx-security-monitor/scripts:ro
    env_file:
      - ../../.env
