# NGINX Security Monitor Configuration
# This configuration file matches the schema.yml structure for validation

# ============================================================================
# Service Settings
# ============================================================================
service:
  check_interval: 60
  log_file_path: "/var/log/nginx-security-monitor.log"
  error_log_file_path: "/var/log/nginx-security-monitor-error.log"

# ============================================================================
# Alert Settings
# ============================================================================
alerts:
  enabled: true
  channels:
    - email

  console:
    enabled: true
    color: true
    verbose: false

  email:
    enabled: true
    smtp_server: "smtp.example.com"
    smtp_port: 587
    use_tls: true
    username: "your_email@example.com"
    password: "your_email_password"
    from_address: "your_email@example.com"
    to_addresses:
      - "alert_recipient@example.com"

# ============================================================================
# Mitigation Settings
# ============================================================================
mitigation:
  enabled: true
  auto_mitigation: false
  strategies:
    ip_blocking:
      enabled: true
      duration: 300
      max_attempts: 5
    rate_limiting:
      enabled: true
      requests_per_minute: 60
      burst_allowance: 10

# ============================================================================
# Service Protection Settings
# ============================================================================
service_protection:
  resource_thresholds:
    cpu_percent: 80.0
    memory_percent: 80.0
    disk_usage_percent: 90.0
  whitelist:
    processes: []

# ============================================================================
# Network Security Settings
# ============================================================================
network_security:
  max_failed_attempts: 5

# ============================================================================
# Cryptographic Settings
# ============================================================================
crypto:
  base_delay: 0.1
  max_delay: 1.0

# ============================================================================
# Monitoring Settings
# ============================================================================
monitoring:
  enabled: true
  check_interval: 30
  batch_size: 100
  debug_mode: false
  logging_level: "INFO"
  log_tail: true
  log_files:
    - "/var/log/nginx/access.log"
    - "/var/log/nginx/error.log"

# ============================================================================
# Log File Settings
# ============================================================================
logs:
  access_log: "/var/log/nginx/access.log"
  error_log: "/var/log/nginx/error.log"
  format: "combined"
  encoding: "utf-8"
  verbose_parsing: false

# ============================================================================
# Detection Settings
# ============================================================================
detection:
  enabled_patterns:
    - "sql_injection"
    - "xss_attacks" 
    - "ddos_detection"
    - "brute_force"
    - "directory_traversal"
    - "suspicious_user_agents"
  thresholds:
    failed_requests_per_minute: 10
    requests_per_ip_per_minute: 60
    error_rate_threshold: 0.1
    suspicious_user_agent_threshold: 5
    sensitivity: "medium"
  whitelist:
    ips: []
    user_agents: []
    processes:
      - name: "nginx"
        description: "NGINX worker processes"
      - name: "nginx: master process nginx"
        description: "NGINX master process"
      - name: "nginx: worker process"
        description: "NGINX worker process"

# ============================================================================
# Pattern Detection Settings
# ============================================================================
pattern_detection:
  thresholds:
    sql_injection: 5
    xss_attacks: 5
    ddos_detection: 100
    brute_force: 10
    directory_traversal: 5
    suspicious_user_agents: 5

# ============================================================================
# Logging Settings
# ============================================================================
logging:
  level: "INFO"
  file: "/var/log/nginx-security-monitor.log"
  max_size: "10MB"
  backup_count: 5
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
  console: true
  stdout: false
  verbose: false

# ============================================================================
# Storage Settings
# ============================================================================
storage:
  database:
    type: "sqlite"
    path: "/var/lib/nginx-security-monitor/monitor.db"
  cache:
    enabled: true
    type: "memory"
    max_size: 1000
    ttl: 3600

# ============================================================================
# Security Settings
# ============================================================================
security:
  encryption:
    enabled: true
    key_path: "/etc/nginx-security-monitor/encryption.key"
  plugin_security:
    enabled: true
    allowed_plugins_dir: "/opt/nginx-security-monitor/plugins"
    signature_verification: true
    whitelist: []