# NGINX Security Monitor Configuration
# This file controls all aspects of the monitoring service

# ============================================================================
# Core Settings
# ============================================================================
monitoring:
  enabled: true
  check_interval: 10  # seconds between log checks
  batch_size: 1000    # number of log entries to process at once
  
# ============================================================================  
# Log File Settings
# ============================================================================
logs:
  access_log: "/var/log/nginx/access.log"
  error_log: "/var/log/nginx/error.log"
  format: "combined"  # nginx log format
  encoding: "utf-8"
  
# ============================================================================
# Pattern Detection Settings  
# ============================================================================
detection:
  enabled_patterns:
    - sql_injection
    - xss_attacks
    - ddos_detection
    - brute_force
    - directory_traversal
    - suspicious_user_agents
  
  thresholds:
    failed_requests_per_minute: 50
    requests_per_ip_per_minute: 100
    error_rate_threshold: 0.1
    suspicious_user_agent_threshold: 5
  
  whitelist:
    ips:
      - "127.0.0.1"
      - "::1"
      - "192.168.1.0/24"
    user_agents:
      - "Googlebot"
      - "Bingbot"
    
# ============================================================================
# Alert Settings
# ============================================================================
alerts:
  enabled: true
  channels:
    - email
    - sms
  
  email:
    enabled: true
    smtp_server: "smtp.gmail.com"
    smtp_port: 587
    use_tls: true
    username: "your_email@gmail.com"
    password: "<REPLACE_WITH_ENV_VARIABLE>"  # Use app passwords for Gmail
    from_address: "your_email@gmail.com"
    to_addresses:
      - "security@yourdomain.com"
      - "admin@yourdomain.com"
    
    templates:
      subject: "[SECURITY ALERT] {severity} - {attack_type} detected"
      body_format: "html"  # html or text
  
  sms:
    enabled: false
    provider: "twilio"  # twilio, aws_sns, custom
    # Add provider-specific settings here
    
# ============================================================================
# Mitigation Settings
# ============================================================================
mitigation:
  enabled: true
  auto_mitigation: false  # Set to true for automatic responses
  
  strategies:
    ip_blocking:
      enabled: true
      duration: 3600  # seconds to block IP
      max_attempts: 10
    
    rate_limiting:
      enabled: true
      requests_per_minute: 60
      burst_allowance: 10
      
# ============================================================================
# Logging Settings
# ============================================================================
logging:
  level: "INFO"  # DEBUG, INFO, WARNING, ERROR, CRITICAL
  file: "/var/log/nginx-security-monitor.log"
  max_size: "10MB"
  backup_count: 5
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
  
# ============================================================================
# Storage Settings
# ============================================================================
storage:
  database:
    type: "sqlite"  # sqlite, postgresql, mysql
    path: "/var/lib/nginx-security-monitor/monitor.db"
    
  cache:
    type: "memory"  # memory, redis
    max_size: 1000
    ttl: 3600
    
# ============================================================================
# Security Settings
# ============================================================================
security:
  encryption:
    enabled: false
    key_file: "<REPLACE_WITH_ENV_VARIABLE>"
    
  plugin_security:
    enabled: true
    allowed_plugins_dir: "/etc/nginx-security-monitor/plugins"
    signature_verification: false